title: LQC
description: A community of qualitative researchers in London
theme: just-the-docs

url: https://londonqualcommunity.com

aux_links:
  GitHub Repository: https://github.com/linxule/lqc

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Logo and favicon
logo: "/asset/icon.png"
favicon_ico: "/asset/icon.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true