title: L+QC
description: A community of qualitative researchers in London
theme: just-the-docs

url: https://londonqualcommunity.com

aux_links:
  L+QC on GitHub: https://github.com/linxule/lqc
  LinkedIn: https://www.linkedin.com/groups/12947079/

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Logo and favicon
logo: "/assets/logos/logo.png"
favicon_ico: "/assets/logos/icon.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Automatic freshness indicator
last_edit_timestamp: true
last_edit_time_format: "%b %d, %Y"

# Back to top for long pages
back_to_top: true
back_to_top_text: "Back to top"

# Hide pages
exclude:
  - discussions/