title: London Qualitative Community
description: A community of qualitative researchers in London
theme: just-the-docs

url: https://linxule.github.io/lqc

aux_links:
  Template Repository: https://github.com/linxule/lqc
