title: LQC
description: A community of qualitative researchers in London
theme: just-the-docs

url: https://londonqualcommunity.com

aux_links:
  LQC on GitHub: https://github.com/linxule/lqc

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Logo and favicon
logo: "/assets/logos/logo.png"
favicon_ico: "/assets/logos/icon.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Hide pages 
exclude:
  - discussions/